
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getShellInfo() : Promise<ShellInfo> {
    return await TAURI_INVOKE("get_shell_info");
},
/**
 * Constructs a brand-new, in-memory `ProjectV1` with sensible defaults.
 * Deliberately does not touch the filesystem: wiring this into a real
 * Project Manager UI (recent projects, save/open, `project.json` on disk)
 * is later-phase work. This command exists in Phase 2 to exercise the real
 * `ProjectV1` schema (`docs/project-format.md`) end-to-end over IPC and
 * through specta-generated TypeScript types — it is not a placeholder for
 * "create project" functionality, just proof the schema/IPC layer works.
 */
async newProject(name: string) : Promise<ProjectV1> {
    return await TAURI_INVOKE("new_project", { name });
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AiState = { 
/**
 * Opaque id — actual credentials live in the Windows Credential
 * Manager, never in `project.json` (master prompt §17, Phase 10).
 */
provider_settings_ref: string | null; 
/**
 * Most recent `EditPlan` JSON (`docs/ai-engine.md`, Phase 10). Opaque
 * here for the same reason as `Effect::params`: the schema doesn't
 * exist yet.
 */
last_edit_plan: JsonValue | null; highlights: JsonValue[] }
export type Animation = { id: string; clip_id: string; kind: AnimationKind; name: string; duration_us: number }
export type AnimationKind = "in" | "out" | "loop" | "group"
export type CanvasRatioPreset = "16:9" | "9:16" | "1:1" | "4:5" | "custom"
export type CanvasV1 = { width: number; height: number; fps: Rational; ratio_preset: CanvasRatioPreset }
export type Caption = { id: string; track_id: string; start_us: number; end_us: number; text: string; words: Word[]; style_id: string | null }
export type Clip = { id: string; track_id: string; 
/**
 * `None` for e.g. a pure-effect or generated-caption clip.
 */
media_id: string | null; 
/**
 * Trim into the source media.
 */
source_in_us: number; source_out_us: number; 
/**
 * Placement on the track's timeline.
 */
position_us: number; speed: number; enabled: boolean; 
/**
 * `SyncGroup` membership, see `SyncGroup` below.
 */
group_id: string | null; clip_settings: ClipSettings }
export type ClipSettings = { opacity: number; flip_h: boolean; flip_v: boolean; rotation_deg: number; scale_x: number; scale_y: number; 
/**
 * Half-canvas-width/height units, matching pyJianYingDraft's
 * `transform_x`/`transform_y` convention (audit §1) — NOT pixels. A
 * frequent bug source upstream; documented here so it isn't
 * rediscovered the hard way in the render/capcut adapters.
 */
transform_x: number; transform_y: number }
/**
 * Edit-plan / silence-removal provenance — NOT a duplicate timeline.
 * Records *why* clips were split/removed by an automated pass (VAD, AI
 * EditPlan), for undo/audit/re-analysis (`docs/project-format.md`).
 */
export type Cut = { id: string; kind: CutKind; source_media_id: string; start_us: number; end_us: number; reason: CutReason; applied: boolean }
export type CutKind = "remove" | "keep"
export type CutReason = "silence" | "filler_word" | "ai_suggested"
export type Effect = { id: string; clip_id: string; kind: string; 
/**
 * Freeform, effect-kind-specific parameters. Kept as opaque JSON here
 * deliberately — the effect catalog/parameter schemas don't exist yet
 * (Phase 6+), so a closed Rust struct would just be guessing.
 */
params: JsonValue }
export type ExportState = { last_render_preset: string | null; last_capcut_draft_path: string | null }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type Keyframe = { id: string; clip_id: string; 
/**
 * One of `position_x | position_y | rotation | scale | alpha | volume`
 * and more as the property catalog grows (`docs/project-format.md`
 * leaves this open-ended) — kept as `String` rather than a closed enum
 * so adding a keyframeable property doesn't require a schema-breaking
 * migration.
 */
property: string; time_offset_us: number; value: number; 
/**
 * pyJianYingDraft hardcodes linear-only interpolation today (audit
 * §1); `curve` is a `String` (not a unit enum) so bezier/ease support
 * can be added later without another schema version bump.
 */
curve: string }
export type MediaItem = { id: string; kind: MediaKind; 
/**
 * Absolute or project-relative path.
 */
source_path: string; duration_us: number; width: number; height: number; fps: Rational; codec: string; bitrate: number; audio_channels: number; sample_rate: number; rotation_deg: number; 
/**
 * RFC3339 timestamp, or `None` if the source has no embedded creation
 * time.
 */
created_at: string | null; proxy_path: string | null; thumbnail_path: string | null }
export type MediaKind = "video" | "audio" | "image"
export type ProjectMeta = { id: string; name: string; 
/**
 * RFC3339 timestamp.
 */
created_at: string; 
/**
 * RFC3339 timestamp.
 */
modified_at: string; 
/**
 * semver of the app version that wrote this file.
 */
app_version: string }
/**
 * The unified project file (`project.json`). See `docs/project-format.md`
 * for the full design rationale — stable UUID-based ids everywhere,
 * non-destructive (never stores rendered pixels/audio), versioned for
 * forward migration.
 */
export type ProjectV1 = { 
/**
 * Always `1` for this schema version. `ProjectV1::migrate_to_latest`
 * dispatches on this field.
 */
version: number; project: ProjectMeta; canvas: CanvasV1; media: MediaItem[]; tracks: Track[]; clips: Clip[]; captions: Caption[]; transcript: TranscriptEntry[]; effects: Effect[]; animations: Animation[]; keyframes: Keyframe[]; cuts: Cut[]; ai: AiState; export: ExportState; sync_groups: SyncGroup[] }
/**
 * A rational number, used for frame rates (`num/den`, e.g. 30000/1001 for
 * 29.97 fps) to avoid the float-drift problems documented in autocut's
 * `timecode.rs` (audit §2/§5).
 */
export type Rational = { num: number; den: number }
/**
 * Static, build-time facts about this build. No telemetry, no network
 * calls, nothing environment-dependent beyond `std::env::consts`. Exists in
 * Phase 2 to exercise the Rust -> specta -> TypeScript pipeline end-to-end
 * with a genuinely working command; the full Settings > About / "Copy
 * System Information" panel (master prompt §78) is Phase 12 scope.
 */
export type ShellInfo = { app_version: string; tauri_version: string; os: string; arch: string }
/**
 * Generalizes autocut's fixed-camera-rig "shared cutlist + per-track
 * offset" concept (audit §4) into a first-class, optional relationship. A
 * clip's `Clip::group_id` points at a `SyncGroup`; the timeline engine
 * (Phase 4) propagates split/trim/delete across all members unless the
 * user explicitly ungroups.
 */
export type SyncGroup = { id: string; 
/**
 * Clips that must move/trim/cut together.
 */
clip_ids: string[]; 
/**
 * Relative alignment, keyed by clip id.
 */
offsets_us: Partial<{ [key in string]: number }> }
export type Track = { id: string; kind: TrackKind; name: string; 
/**
 * Stacking order; higher draws on top (pyJianYingDraft convention,
 * audit §1).
 */
render_index: number; locked: boolean; hidden: boolean; muted: boolean; solo: boolean; 
/**
 * Ordered; the clips themselves live in `ProjectV1::clips`, keyed by
 * id — never store clip data inline here (stable-ID references only,
 * master prompt §5).
 */
clip_ids: string[] }
export type TrackKind = "video" | "audio" | "caption" | "image" | "overlay" | "effect"
export type TranscriptEntry = { id: string; media_id: string; text: string; start_us: number; end_us: number; confidence: number; is_filler: boolean }
export type Word = { text: string; start_us: number; end_us: number; confidence: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
