
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getShellInfo() : Promise<ShellInfo> {
    return await TAURI_INVOKE("get_shell_info");
},
/**
 * Detects every confirmed CapCut/Jianying draft-root installation on this
 * machine (filesystem-based — see `crate::capcut::detect` module doc
 * comment for the full heuristic and its honest limitations). Returns an
 * empty `Vec`, never an error, when nothing is found — "no installation
 * found" is an expected, legitimate outcome (e.g. neither app installed,
 * or running on a non-Windows dev host), not a failure.
 */
async detectCapcutInstallations() : Promise<DetectedCapCutInstallation[]> {
    return await TAURI_INVOKE("detect_capcut_installations");
},
/**
 * Best-effort, additive uninstall-registry hints (see
 * `crate::capcut::detect::scan_uninstall_registry` doc comment for
 * confidence caveats). Always succeeds with an empty `Vec` on failure or
 * on a non-Windows host — never blocks or replaces
 * [`detect_capcut_installations`].
 */
async detectCapcutRegistryHints() : Promise<CapCutRegistryHint[]> {
    return await TAURI_INVOKE("detect_capcut_registry_hints");
},
/**
 * Constructs a brand-new, in-memory `ProjectV1` with sensible defaults.
 * Deliberately does not touch the filesystem: wiring this into a real
 * Project Manager UI (recent projects, save/open, `project.json` on disk)
 * is later-phase work. This command exists in Phase 2 to exercise the real
 * `ProjectV1` schema (`docs/project-format.md`) end-to-end over IPC and
 * through specta-generated TypeScript types — it is not a placeholder for
 * "create project" functionality, just proof the schema/IPC layer works.
 */
async newProject(name: string) : Promise<ProjectV1> {
    return await TAURI_INVOKE("new_project", { name });
},
async ffmpegDiagnostics() : Promise<Result<FfmpegDiagnostics, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ffmpeg_diagnostics") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async probeMediaFile(path: string) : Promise<Result<MediaItem, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("probe_media_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Import an explicit list of files (drag & drop, multi-select file picker).
 * Never aborts on the first bad file — each path gets its own
 * success/error result so a multi-file drop of 50 files with one corrupt
 * clip still imports the other 49 (master prompt §7 "multi-file import").
 */
async importMediaPaths(paths: string[], proxyMode: ProxyMode) : Promise<Result<ImportResult[], AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_media_paths", { paths, proxyMode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Recursively import every supported file under `folder` (master prompt §7
 * "folder import").
 */
async importMediaFolder(folder: string, proxyMode: ProxyMode) : Promise<Result<ImportResult[], AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_media_folder", { folder, proxyMode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * On-demand proxy (re)generation, e.g. a user flipping Proxy mode from Off
 * to Always after already importing. Runs synchronously from the caller's
 * point of view (returns the final path or error) while still emitting the
 * same `media:proxy-progress` events a background import-triggered job
 * would, so one UI progress bar handles both cases.
 */
async generateMediaProxy(mediaId: string, sourcePath: string, mode: ProxyMode) : Promise<Result<string | null, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_media_proxy", { mediaId, sourcePath, mode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async computeMediaWaveform(path: string, bins: number) : Promise<Result<WaveformResult, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("compute_media_waveform", { path, bins }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Generates `count` evenly-spaced frame thumbnails across `[0, duration_us)`
 * for the Phase 4 timeline's clip filmstrip display (master prompt §10
 * "thumbnail strip"). Thin IPC wiring only, per this task's narrow-command
 * exception: reuses the exact same `media::thumbnail::generate_video_thumbnail`
 * single-frame extractor Phase 3 already implemented and tested for the
 * media-library card thumbnail — this command just calls it `count` times
 * at different timestamps. Results are cached under this media id's cache
 * directory (`{media_cache}/{media_id}/strip/{index}.jpg`) so a repeat call
 * for the same media/count (e.g. re-requesting the strip after a zoom
 * change) skips regenerating frames that already exist on disk.
 */
async generateThumbnailStrip(mediaId: string, sourcePath: string, durationUs: number, count: number) : Promise<Result<ThumbnailStripFrame[], AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_thumbnail_strip", { mediaId, sourcePath, durationUs, count }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchMediaLibrary(query: string | null, kind: MediaKind | null, limit: number) : Promise<Result<MediaLibraryEntry[], AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_media_library", { query, kind, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listMediaLibrary(limit: number) : Promise<Result<MediaLibraryEntry[], AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_media_library", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeMediaFromLibrary(id: string) : Promise<Result<null, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_media_from_library", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Loads `project` into the timeline session, replacing whatever was there
 * (fresh undo history, empty clipboard). Called whenever the frontend
 * opens or creates a project.
 */
async loadTimelineProject(project: ProjectV1) : Promise<void> {
    await TAURI_INVOKE("load_timeline_project", { project });
},
/**
 * Fetches the current in-session project (e.g. after a reload, or just to
 * resync).
 */
async getTimelineProject() : Promise<Result<ProjectV1, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_timeline_project") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async splitClip(clipId: string, splitAtUs: number) : Promise<Result<ProjectV1, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("split_clip", { clipId, splitAtUs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async trimClipStart(clipId: string, newStartUs: number) : Promise<Result<ProjectV1, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("trim_clip_start", { clipId, newStartUs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async trimClipEnd(clipId: string, newEndUs: number) : Promise<Result<ProjectV1, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("trim_clip_end", { clipId, newEndUs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async moveClip(clipId: string, targetTrackId: string, newPositionUs: number) : Promise<Result<ProjectV1, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("move_clip", { clipId, targetTrackId, newPositionUs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteClip(clipId: string) : Promise<Result<ProjectV1, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_clip", { clipId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes every clip in `clip_ids` as one atomic undo step — the
 * backend-side multi-select delete (master prompt §11's "composite/batch
 * command" requirement) so the frontend never needs N separate undo
 * entries for one multi-select action.
 */
async deleteClips(clipIds: string[]) : Promise<Result<ProjectV1, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_clips", { clipIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async duplicateClip(clipId: string, newPositionUs: number, targetTrackId: string | null) : Promise<Result<ProjectV1, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("duplicate_clip", { clipId, newPositionUs, targetTrackId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setTrackLocked(trackId: string, locked: boolean) : Promise<Result<ProjectV1, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_track_locked", { trackId, locked }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setTrackHidden(trackId: string, hidden: boolean) : Promise<Result<ProjectV1, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_track_hidden", { trackId, hidden }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setTrackMuted(trackId: string, muted: boolean) : Promise<Result<ProjectV1, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_track_muted", { trackId, muted }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setTrackSolo(trackId: string, solo: boolean) : Promise<Result<ProjectV1, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_track_solo", { trackId, solo }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Pure query, keyed by track id: whether solo state on any audio track
 * currently makes this track's audio effectively muted (master prompt: "if
 * any track has solo = true, all non-solo audio tracks are effectively
 * muted"). For the render/preview layer to consult; not itself an undoable
 * edit.
 */
async effectiveTrackMuteState() : Promise<Result<Partial<{ [key in string]: boolean }>, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("effective_track_mute_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async undoTimeline() : Promise<Result<ProjectV1, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("undo_timeline") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async redoTimeline() : Promise<Result<ProjectV1, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("redo_timeline") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async copyClips(clipIds: string[]) : Promise<Result<null, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("copy_clips", { clipIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pasteClips(targetTrackId: string | null, targetPositionUs: number) : Promise<Result<ProjectV1, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("paste_clips", { targetTrackId, targetPositionUs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Given a target time and a set of candidate snap points (other clip
 * edges, the playhead, markers — supplied by the frontend, which owns that
 * UI-level knowledge), returns the nearest candidate within `threshold_us`,
 * or `None`. Pure function, no session required.
 */
async snapToCandidates(targetUs: number, candidates: number[], thresholdUs: number) : Promise<number | null> {
    return await TAURI_INVOKE("snap_to_candidates", { targetUs, candidates, thresholdUs });
},
/**
 * Applies every `Remove` cut in `cuts` (whose `source_media_id` matches
 * `clip_id`'s media) to `clip_id`: split/trim/delete on the real timeline,
 * as one atomic undo step, marking the applied cuts in `ProjectV1::cuts`.
 */
async applySilenceCuts(clipId: string, cuts: Cut[]) : Promise<Result<ProjectV1, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply_silence_cuts", { clipId, cuts }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Same as `apply_silence_cuts`, but for every clip currently on `track_id`
 * (master prompt §12's "analysis track selection" applied at Apply time).
 */
async applySilenceCutsToTrack(trackId: string, cuts: Cut[]) : Promise<Result<ProjectV1, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply_silence_cuts_to_track", { trackId, cuts }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Creates a `SyncGroup` from `clip_ids` using caller-supplied offsets
 * (microseconds, one per clip id) — the reliable, always-available
 * alignment path (`timeline::sync` module doc comment).
 */
async createSyncGroupManual(clipIds: string[], offsetsUs: Partial<{ [key in string]: number }>) : Promise<Result<ProjectV1, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_sync_group_manual", { clipIds, offsetsUs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Creates a `SyncGroup` from `clip_ids` using each clip's underlying
 * `MediaItem::created_at` (RFC3339 wall-clock timestamp) — best-effort,
 * second-resolution, NOT frame-accurate (`timeline::sync` module doc
 * comment). Fails with `TIMELINE_TIMECODE_UNAVAILABLE` if any involved clip
 * lacks the data; manual offset entry remains the fallback.
 */
async createSyncGroupByTimecode(clipIds: string[]) : Promise<Result<ProjectV1, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_sync_group_by_timecode", { clipIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The six built-in caption style templates (Minimal/TikTok/Podcast/News/
 * Gaming/Karaoke, master prompt §26). Pure — no session required, same
 * pattern as `commands::render::list_render_presets`.
 */
async listCaptionTemplates() : Promise<CaptionStyle[]> {
    return await TAURI_INVOKE("list_caption_templates");
},
/**
 * Replaces the project's own `caption_styles` catalog wholesale. Applied
 * directly to the session (bypassing `Command`/`History`, the same way
 * `load_timeline_project` replaces the whole session) rather than through a
 * new `Command` primitive: `caption_styles` is a settings catalog (like
 * `RenderSettings`), not an independently-addressed timeline entity the way
 * `Caption`/`Clip` are — undoability for *caption* edits (the operations
 * below, which set a caption's `style_id`) is what actually matters for
 * timeline history; editing the style definitions themselves is a
 * settings-form edit, not a timeline edit.
 */
async setCaptionStyles(styles: CaptionStyle[]) : Promise<Result<ProjectV1, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_caption_styles", { styles }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Generates captions from the current session project's own
 * `ProjectV1::transcript`, assigns them all to `track_id`, and inserts them
 * as one atomic undo step (a `Batch` of `InsertCaption`).
 */
async generateCaptions(trackId: string, settings: CaptionGenerationSettings) : Promise<Result<ProjectV1, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_captions", { trackId, settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async splitCaption(captionId: string, splitPoint: CaptionSplitPoint) : Promise<Result<ProjectV1, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("split_caption", { captionId, splitPoint }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async mergeCaptions(captionIds: string[]) : Promise<Result<ProjectV1, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("merge_captions", { captionIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Adjusts a caption's start/end boundary — the same command whether it
 * came from a precise numeric edit or a drag gesture on either edge.
 * `scale_words` decides whether per-word timing is proportionally rescaled
 * to the new span (see `timeline::captions::retime_caption` doc comment).
 */
async retimeCaption(captionId: string, newStartUs: number, newEndUs: number, scaleWords: boolean) : Promise<Result<ProjectV1, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("retime_caption", { captionId, newStartUs, newEndUs, scaleWords }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async findReplaceCaptions(find: string, replace: string, options: FindReplaceOptions) : Promise<Result<ProjectV1, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("find_replace_captions", { find, replace, options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async bulkSetCaptionStyle(captionIds: string[], styleId: string | null) : Promise<Result<ProjectV1, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bulk_set_caption_style", { captionIds, styleId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * **Analyze** (master prompt §12): extracts 16kHz mono PCM from
 * `media_path` and scores it with `SileroVadProvider`, caching the result
 * in `VadCache` under `media_id`. This is the expensive, model-dependent
 * half of the two-phase design — call it once per media file; every
 * subsequent parameter tweak should call `segment_media_silence` instead,
 * not this command again.
 */
async scoreMediaSilence(mediaId: string, mediaPath: string) : Promise<Result<VadScoreSummary, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("score_media_silence", { mediaId, mediaPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * **Preview Cuts' VAD half**: re-segments the *already-cached* chunk scores
 * for `media_id` under new `params` — cheap, pure post-processing, never
 * touches the model. Errors with `VAD_NOT_SCORED` if `score_media_silence`
 * hasn't been called for this `media_id` yet.
 */
async segmentMediaSilence(mediaId: string, params: VadParams) : Promise<Result<SpeechSegment[], AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("segment_media_silence", { mediaId, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * **Preview Cuts' cutlist half**: builds the proposed (`applied: false`)
 * `Remove` cuts from `segments` per `cut_params` — pure, stateless, no
 * caching needed (cheap enough to call on every padding/merge-gap slider
 * change).
 */
async buildSilenceCutlist(sourceMediaId: string, mediaDurationUs: number, segments: SpeechSegment[], cutParams: CutParams) : Promise<Cut[]> {
    return await TAURI_INVOKE("build_silence_cutlist", { sourceMediaId, mediaDurationUs, segments, cutParams });
},
async detectFillerWords(entries: TranscriptEntry[], dictionary: FillerDictionary, cutParams: CutParams) : Promise<Cut[]> {
    return await TAURI_INVOKE("detect_filler_words", { entries, dictionary, cutParams });
},
async listInstalledModels() : Promise<Result<InstalledModel[], AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_installed_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listAvailableModels() : Promise<Result<AvailableModel[], AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_available_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async downloadModel(modelId: string) : Promise<Result<null, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelModelDownload(modelId: string) : Promise<Result<null, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_model_download", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteModel(modelId: string) : Promise<Result<null, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Starts a background transcription job against `media_path`'s audio
 * (extracted via `audio::pcm::extract_pcm`, the same 16kHz-mono pipeline
 * `vad` uses) using the installed model `model_id`. Returns a `job_id`
 * immediately; the real result — `Vec<TranscriptEntry>` with per-word
 * timestamps, `media_id` already filled in, `is_filler: false`, ready to
 * merge into `ProjectV1::transcript` — arrives via the final
 * `transcription:progress` event (`done: true`).
 */
async transcribeMedia(mediaId: string, mediaPath: string, modelId: string, language: string | null) : Promise<Result<string, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transcribe_media", { mediaId, mediaPath, modelId, language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelTranscription(jobId: string) : Promise<Result<null, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_transcription", { jobId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listRenderPresets() : Promise<RenderPreset[]> {
    return await TAURI_INVOKE("list_render_presets");
},
async detectHardwareEncoders() : Promise<Result<HardwareEncoderReport, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("detect_hardware_encoders") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startRenderJob(project: ProjectV1, settings: RenderSettingsInput, outputPath: string) : Promise<Result<string, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_render_job", { project, settings, outputPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelRenderJob(jobId: string) : Promise<Result<null, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_render_job", { jobId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setAiApiKey(credentialRef: string, apiKey: string) : Promise<Result<null, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_ai_api_key", { credentialRef, apiKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteAiApiKey(credentialRef: string) : Promise<Result<null, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_ai_api_key", { credentialRef }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Calls the configured provider with a trivial request and reports
 * success/failure — never returns a stored API key to the frontend
 * (module doc comment). Folds every failure mode (missing key, unreachable
 * endpoint, bad credentials, malformed response) into
 * `AiConnectionTestResult { success: false, .. }` rather than an `Err`, so
 * the frontend can render a plain pass/fail indicator without a thrown
 * error.
 */
async testAiConnection(settings: AiProviderSettings) : Promise<AiConnectionTestResult> {
    return await TAURI_INVOKE("test_ai_connection", { settings });
},
/**
 * **Validate** (master prompt §18's "JSON Schema validation" stage): parses
 * `raw` (whatever text an `AIProvider::complete` returned) into a strict
 * `EditPlan`, or a specific validation error — never a partially-populated
 * plan. The frontend's Edit Plan Preview (a later pass) is built on the
 * `EditPlan` this returns.
 */
async validateEditPlan(raw: string) : Promise<Result<EditPlan, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_edit_plan", { raw }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Pure conversion of an already-validated plan's `Remove` operations into
 * unapplied `Cut`s scoped to `source_media_id` — the same
 * "propose the cutlist, don't apply it yet" step
 * `commands::vad::build_silence_cutlist` already exposes for VAD-derived
 * cuts. `Zoom` operations are dropped here (`edit_plan` module doc comment
 * — structural-only in this pass).
 */
async buildCutsFromEditPlan(sourceMediaId: string, plan: EditPlan) : Promise<Cut[]> {
    return await TAURI_INVOKE("build_cuts_from_edit_plan", { sourceMediaId, plan });
},
/**
 * **Apply** (master prompt §18's "User Approves → Timeline Engine" stage,
 * scoped to one clip): converts `plan`'s `Remove` operations into `Cut`s
 * against `source_media_id` and applies them to `clip_id` through the
 * exact same split/trim/delete → `Command::Batch` → undo-history path
 * `commands::timeline::apply_silence_cuts` already provides for VAD/
 * filler-word cuts — one atomic undo step, never a second mutation path.
 */
async applyEditPlanToClip(clipId: string, sourceMediaId: string, plan: EditPlan) : Promise<Result<ProjectV1, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply_edit_plan_to_clip", { clipId, sourceMediaId, plan }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Same as [`apply_edit_plan_to_clip`], but for every clip currently on
 * `track_id` (delegates to `commands::timeline::apply_silence_cuts_to_track`).
 */
async applyEditPlanToTrack(trackId: string, sourceMediaId: string, plan: EditPlan) : Promise<Result<ProjectV1, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply_edit_plan_to_track", { trackId, sourceMediaId, plan }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * **Natural language → AI Provider → EditPlan → Schema validation**
 * (master prompt §20's pipeline, up through validation — Preview/Apply are
 * the existing [`build_cuts_from_edit_plan`]/[`apply_edit_plan_to_clip`]/
 * [`apply_edit_plan_to_track`] commands above, reused unchanged): builds a
 * real grounding prompt from `nl_command` + `transcript` + `total_duration_us`
 * (`ai::nl_command::build_edit_plan_prompt`), calls the configured
 * provider, and validates the response through the exact same
 * `edit_plan::parse_and_validate` [`validate_edit_plan`] already uses —
 * never a second, parallel validation path. Never a partially-populated
 * plan: any malformed/invalid response is a clear `AppErrorPayload`, not a
 * best-effort guess.
 * 
 * See `ai::nl_command` module doc comment for exactly which of master
 * prompt §20's own example commands this can express end-to-end today
 * (pure removal/timing edits) versus which need operation kinds this pass's
 * `EditPlan` schema doesn't have yet.
 */
async generateEditPlanFromNlCommand(settings: AiProviderSettings, nlCommand: string, transcript: TranscriptEntry[], totalDurationUs: number) : Promise<Result<EditPlan, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_edit_plan_from_nl_command", { settings, nlCommand, transcript, totalDurationUs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * **Analyze**: builds a Smart Edit prompt from `entries` (the caller-
 * supplied transcript — same "caller passes the transcript in directly"
 * convention `commands::transcription::detect_filler_words` already uses,
 * rather than this command reaching into project state itself), calls the
 * configured provider, and validates the response into a strict
 * `Vec<SmartEditRecommendation>` — or a clear error, never a partially
 * populated result (`ai::smart_edit` module doc comment).
 * 
 * This is a *proposal* the frontend shows the user for review (a later
 * pass) — nothing here mutates the timeline. See
 * [`apply_smart_edit_recommendations_to_clip`]/
 * [`apply_smart_edit_recommendations_to_track`] for the separate, explicit
 * apply step.
 */
async analyzeSmartEdit(settings: AiProviderSettings, entries: TranscriptEntry[]) : Promise<Result<SmartEditRecommendation[], AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("analyze_smart_edit", { settings, entries }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Pure conversion of a caller-selected (and possibly action-overridden)
 * subset of recommendations into unapplied `Cut`s scoped to
 * `source_media_id` — the same "propose the cutlist, don't apply it yet"
 * step [`build_cuts_from_edit_plan`] already exposes for `EditPlan`-derived
 * cuts.
 */
async buildCutsFromSmartEditRecommendations(sourceMediaId: string, recommendations: SmartEditRecommendation[]) : Promise<Cut[]> {
    return await TAURI_INVOKE("build_cuts_from_smart_edit_recommendations", { sourceMediaId, recommendations });
},
/**
 * **Apply** (scoped to one clip): converts `recommendations`' `Remove`/
 * `Shorten` actions into `Cut`s against `source_media_id` and applies them
 * to `clip_id` through the exact same `commands::timeline::apply_silence_cuts`
 * path VAD/filler-word/`EditPlan` cuts already use — one atomic undo step,
 * never a second mutation path. `Keep`/`Highlight` recommendations in
 * `recommendations` simply produce no `Cut` (module doc comment).
 */
async applySmartEditRecommendationsToClip(clipId: string, sourceMediaId: string, recommendations: SmartEditRecommendation[]) : Promise<Result<ProjectV1, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply_smart_edit_recommendations_to_clip", { clipId, sourceMediaId, recommendations }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Same as [`apply_smart_edit_recommendations_to_clip`], but for every clip
 * currently on `track_id` (delegates to
 * `commands::timeline::apply_silence_cuts_to_track`).
 */
async applySmartEditRecommendationsToTrack(trackId: string, sourceMediaId: string, recommendations: SmartEditRecommendation[]) : Promise<Result<ProjectV1, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply_smart_edit_recommendations_to_track", { trackId, sourceMediaId, recommendations }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Real, non-AI scene-change detection on its own (`media::scene`,
 * master prompt §21's "scene changes" signal) — exposed as its own command
 * so a caller can use it independently of the full highlight pipeline
 * below (e.g. a future scene-markers timeline feature, per
 * `IMPLEMENTATION_PLAN.md` Phase 11).
 */
async detectMediaSceneChanges(mediaPath: string, threshold: number | null) : Promise<Result<number[], AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("detect_media_scene_changes", { mediaPath, threshold }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Runs highlight detection end-to-end for one real media file (master
 * prompt §21's full signal list: transcript, speech density, audio energy,
 * scene changes, and — only when `ai_settings` is `Some` — semantic
 * importance). No real AI provider call is ever attempted unless the
 * caller passes real `ai_settings` (module doc comment).
 */
async detectHighlights(mediaPath: string, transcript: TranscriptEntry[], totalDurationUs: number, aiSettings: AiProviderSettings | null, maxHighlights: number | null) : Promise<Result<HighlightDetectionResult, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("detect_highlights", { mediaPath, transcript, totalDurationUs, aiSettings, maxHighlights }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: export `project` as a FCPXML 1.11 file at `output_path`.
 * Specta-typed, following `commands/timeline.rs`/`commands/vad.rs`'s
 * naming/error-envelope conventions.
 */
async exportFcpxml(project: ProjectV1, outputPath: string) : Promise<Result<null, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_fcpxml", { project, outputPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command: export `project` as a CapCut/Jianying draft folder at
 * `draft_output_path`. Specta-typed, following `fcpxml::export::export_fcpxml`'s
 * naming/error-envelope convention.
 */
async exportProjectToCapcutDraft(project: ProjectV1, draftOutputPath: string) : Promise<Result<null, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_project_to_capcut_draft", { project, draftOutputPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AiConnectionTestResult = { success: boolean; 
/**
 * Human-readable outcome — the provider's own trivial reply on
 * success, or an error message on failure. Never a raw API key, on
 * either path.
 */
message: string }
/**
 * Which wire protocol a configured provider profile speaks. `OpenAi`,
 * `Ollama`, and `CustomOpenAiCompatible` all construct the same
 * `OpenAiCompatProvider` (`ai::openai_compat` module doc comment) — they
 * are still distinct variants here because the *frontend* still needs to
 * tell them apart for defaults/labeling/whether a key is normally required,
 * even though the backend adapter code doesn't.
 */
export type AiProviderKind = "open_ai" | "ollama" | "custom_open_ai_compatible" | "anthropic" | "gemini"
/**
 * Master prompt §17's exact settings list (Provider/Base URL/Model/
 * Temperature/Timeout), minus API Key — the key itself never travels
 * through this struct; `credential_ref`, if present, names where
 * [`credentials::CredentialStore`] should look one up.
 */
export type AiProviderSettings = { provider: AiProviderKind; base_url: string; model: string; temperature: number; timeout_ms: number; 
/**
 * `None` for a provider that needs no auth (e.g. a local Ollama
 * instance).
 */
credential_ref: string | null }
export type AiState = { 
/**
 * Opaque id — actual credentials live in the Windows Credential
 * Manager, never in `project.json` (master prompt §17, Phase 10). Never
 * carries a secret itself; see `ai::credentials` module doc comment.
 */
provider_settings_ref: string | null; 
/**
 * Most recent validated `EditPlan` (Phase 10, `ai::edit_plan`) — a
 * real, strictly-typed schema (master prompt §18), not opaque JSON:
 * unlike `Effect::params`, this schema exists and is closed by
 * construction (`EditOperation`'s `#[serde(tag = "type")]` enum), so
 * there is no "schema doesn't exist yet" reason left to keep this
 * field as `serde_json::Value`. `None` until an EditPlan has been
 * validated at least once for this project.
 */
last_edit_plan: EditPlan | null; 
/**
 * Most recent detected highlights (Phase 10 follow-up,
 * `crate::highlights`, master prompt §21) — a real, strictly-typed
 * `{id, start_us, end_us, score, title, reason}` schema
 * (`crate::highlights::types::Highlight`), not opaque JSON: like
 * `last_edit_plan` above, the schema now exists and is closed by
 * construction, so there is no "schema doesn't exist yet" reason left
 * to keep this field as `serde_json::Value`. Empty until highlight
 * detection has been run at least once for this project.
 */
highlights: Highlight[] }
export type Animation = { id: string; clip_id: string; kind: AnimationKind; name: string; duration_us: number }
export type AnimationKind = "in" | "out" | "loop" | "group"
export type AppErrorPayload = { code: string; message: string; details: string | null; recoverable: boolean; suggested_action: string | null }
export type AudioCodec = "aac" | "opus" | "vorbis"
/**
 * Catalog entry cross-referenced with what's actually on disk / actively
 * downloading (master prompt §60 "Available models").
 */
export type AvailableModel = { entry: ModelCatalogEntry; installed: boolean; download_in_progress: boolean }
export type CanvasRatioPreset = "16:9" | "9:16" | "1:1" | "4:5" | "custom"
export type CanvasV1 = { width: number; height: number; fps: Rational; ratio_preset: CanvasRatioPreset }
/**
 * Which product's AppData folder name a candidate draft root was built
 * under. Both are checked for every candidate user profile — see this
 * module's doc comment for why the reference JS's Jianying-only list is
 * extended here.
 */
export type CapCutProduct = 
/**
 * China-region 剪映专业版 (Jianying Pro) — `AppData\Local\JianyingPro`.
 */
"jianying" | 
/**
 * International CapCut — `AppData\Local\CapCut`.
 */
"cap_cut"
/**
 * One uninstall-registry hit that looks like a CapCut/Jianying install,
 * found by [`registry::scan_uninstall_entries`]. Deliberately a separate
 * shape from [`DetectedCapCutInstallation`] rather than merged into it: a
 * registry entry can exist with no matching draft folder yet (installed but
 * never launched) and carries different fields (a version string, an
 * installer-reported location that may or may not be the actual draft
 * root) — conflating the two would mean either fabricating fields on one
 * side or silently dropping information on the other.
 */
export type CapCutRegistryHint = { product: CapCutProduct; display_name: string; display_version: string | null; install_location: string | null }
/**
 * Sorted, non-overlapping by construction: every producer in
 * `captions::generate`/`timeline::captions` builds `words` in time order
 * (word-grouping walks the source transcript left-to-right; split/merge/
 * retime only ever slice or concatenate existing time-ordered runs). The
 * frontend's active-word-at-time-T lookup (master prompt §27) can therefore
 * binary-search `words` by `start_us`/`end_us` in O(log n) per frame instead
 * of a linear scan — this module doesn't implement that search itself (a
 * frontend rendering concern), but the data shape guarantees it works.
 */
export type Caption = { id: string; track_id: string; start_us: number; end_us: number; text: string; words: Word[]; style_id: string | null }
export type CaptionAlignment = "left" | "center" | "right"
/**
 * Vertical placement anchor. Combined with `offset_x`/`offset_y` (see
 * `CaptionPosition`) rather than raw pixels so a caption's position stays
 * correct across different canvas resolutions, same rationale as
 * `ClipSettings::transform_x/y`.
 */
export type CaptionAnchor = "top" | "center" | "bottom"
export type CaptionBackground = { color: Color; opacity: number }
export type CaptionGenerationSettings = { 
/**
 * Maximum words on one caption's line. Values `< 1` are treated as `1`
 * (a defensive floor, not an error — generation always produces
 * *something* rather than failing on a degenerate settings value).
 */
max_words_per_line: number; 
/**
 * Maximum characters (Unicode scalar count, not bytes) on one caption's
 * line, joined-with-single-spaces. Same `< 1` floor as above.
 */
max_chars_per_line: number; grouping: CaptionGroupingMode }
/**
 * Serde/specta-typed (not just an internal Rust enum) so it can cross the
 * Tauri IPC boundary directly as a `commands::captions::generate_captions`
 * parameter, the same way `render::presets::RenderSettings` is typed for
 * `commands::render::start_render_job` despite not being part of
 * `ProjectV1` either.
 */
export type CaptionGroupingMode = 
/**
 * One caption per transcript entry (further wrapped only if the entry
 * itself exceeds the line limits).
 */
"sentence" | 
/**
 * A single continuous word stream across every entry, chunked strictly
 * by the line limits, ignoring sentence boundaries.
 */
"word"
export type CaptionOutline = { color: Color; 
/**
 * Stroke width as a fraction of font size — matches pyJianYingDraft's
 * `TextBorder` convention (capcut-mate `add_captions.py` hardcodes
 * `width: 0.08` for exactly this reason), so Phase 9's CapCut adapter
 * needs no unit conversion.
 */
width: number }
export type CaptionPosition = { anchor: CaptionAnchor; 
/**
 * Half-canvas-width/height units, the exact same convention as
 * `ClipSettings::transform_x`/`transform_y` above — NOT pixels, and NOT
 * a second unit system invented for captions.
 */
offset_x: number; offset_y: number }
export type CaptionShadow = { color: Color; opacity: number; 
/**
 * Half-canvas-width/height units (same convention as `CaptionPosition`).
 */
offset_x: number; offset_y: number; 
/**
 * Blur/diffuse radius, same `0..=100` scale as pyJianYingDraft's
 * `TextShadow.diffuse` (capcut-mate default `15.0`). Phase 9's adapter
 * derives CapCut's `distance`/`angle` pair from `offset_x`/`offset_y`
 * via `hypot`/`atan2` at that boundary — never stored redundantly here.
 */
blur: number }
/**
 * Where to split a caption: either an absolute timeline instant, or a
 * direct index into its `words` (0 = before the first word). Splitting
 * requires per-word timing (`Caption::words` non-empty) — without it there
 * is no principled way to decide which characters of `text` belong to which
 * half, so this is rejected rather than guessed at.
 */
export type CaptionSplitPoint = { time_us: number } | { word_index: number }
/**
 * Caption visual styling (master prompt §26's exact field list). Referenced
 * by `Caption::style_id`; the catalog of built-in templates lives in
 * `crate::captions::styles::all_caption_templates` (Minimal/TikTok/Podcast/
 * News/Gaming/Karaoke), following the same "catalog function returning
 * owned values" pattern as `render::presets::all_presets`.
 */
export type CaptionStyle = { id: string; name: string; font_family: string; font_size: number; bold: boolean; italic: boolean; alignment: CaptionAlignment; position: CaptionPosition; text_color: Color; 
/**
 * `None` = no background box behind the text (capcut-mate's own
 * `TextStyle` has no native background-box field — Phase 9's adapter
 * will need to synthesize one via an extra shape/rect segment when this
 * is `Some`; documented here so that gap isn't rediscovered then).
 */
background: CaptionBackground | null; outline: CaptionOutline | null; shadow: CaptionShadow | null; opacity: number; safe_margins: SafeMargins }
export type Clip = { id: string; track_id: string; 
/**
 * `None` for e.g. a pure-effect or generated-caption clip.
 */
media_id: string | null; 
/**
 * Trim into the source media.
 */
source_in_us: number; source_out_us: number; 
/**
 * Placement on the track's timeline.
 */
position_us: number; speed: number; enabled: boolean; 
/**
 * `SyncGroup` membership, see `SyncGroup` below.
 */
group_id: string | null; clip_settings: ClipSettings }
export type ClipSettings = { opacity: number; flip_h: boolean; flip_v: boolean; rotation_deg: number; scale_x: number; scale_y: number; 
/**
 * Half-canvas-width/height units, matching pyJianYingDraft's
 * `transform_x`/`transform_y` convention (audit §1) — NOT pixels. A
 * frequent bug source upstream; documented here so it isn't
 * rediscovered the hard way in the render/capcut adapters.
 */
transform_x: number; transform_y: number }
/**
 * A color in linear `[0.0, 1.0]` per-channel form — matches capcut-mate's
 * own `hex_to_rgb` convention (`vendor/capcut-mate/src/service/add_captions.py`)
 * so Phase 9's CapCut adapter can hand these straight to `TextStyle`/
 * `TextBorder`/`TextShadow` without a hex round-trip. Hex string
 * conversion (for a color-picker UI) is a frontend/adapter-boundary
 * concern, not this schema's.
 */
export type Color = { r: number; g: number; b: number }
export type Container = "mp_4" | "web_m"
/**
 * Edit-plan / silence-removal provenance — NOT a duplicate timeline.
 * Records *why* clips were split/removed by an automated pass (VAD, AI
 * EditPlan), for undo/audit/re-analysis (`docs/project-format.md`).
 */
export type Cut = { id: string; kind: CutKind; source_media_id: string; start_us: number; end_us: number; reason: CutReason; applied: boolean }
export type CutKind = "remove" | "keep"
/**
 * Everything master prompt §12 lists that isn't already a `VadParams`
 * concern (threshold/min-silence/min-speech live in `super::provider`,
 * applied *before* this stage ever sees the segments).
 */
export type CutParams = { padding_before_us: number; padding_after_us: number; 
/**
 * "Merge nearby speech": two kept (already-padded) regions closer than
 * this are merged into one, purely for a cleaner preview — this never
 * re-runs VAD segmentation.
 */
merge_gap_us: number }
export type CutReason = "silence" | "filler_word" | "ai_suggested"
/**
 * One confirmed CapCut/Jianying draft-root installation.
 */
export type DetectedCapCutInstallation = { product: CapCutProduct; 
/**
 * The user-profile home directory this installation was found under
 * (e.g. `C:\Users\Alice`), as a display string — see `crate::commands`
 * convention of exposing filesystem paths as `String`, not `PathBuf`,
 * over the Tauri/specta boundary.
 */
user_profile: string; 
/**
 * The confirmed draft-root directory itself
 * (`...\User Data\Projects\com.lveditor.draft`).
 */
draft_root: string; 
/**
 * Whether `root_meta_info.json` (a file) was found directly inside
 * `draft_root`.
 */
has_root_meta_info: boolean; 
/**
 * Whether a `.recycle_bin` directory was found directly inside
 * `draft_root`. Either this or `has_root_meta_info` is always `true`
 * for a value that made it into a result `Vec` — that's the
 * confirmation condition (see [`confirm_draft_root`]).
 */
has_recycle_bin: boolean }
export type DetectedEncoder = { backend: EncoderBackend; label: string; h264_encoder: string; h265_encoder: string; 
/**
 * `true` only if the encoder was both listed by `ffmpeg -encoders` AND
 * passed a real smoke-test encode on this machine.
 */
working: boolean }
/**
 * A single edit action (master prompt §18's example: `{"type": "remove",
 * "start": 12.3, "end": 15.7, "reason": "long pause"}` /
 * `{"type": "zoom", "start": 32, "end": 36, "scale": 1.12}`). Time fields
 * are `_us` microseconds per this crate's own timebase convention
 * (`project::types` module doc comment), not the master prompt's own
 * float-seconds example — every other timestamp in this schema
 * (`Cut`/`Clip`/`Caption`/...) already made that same conversion.
 */
export type EditOperation = 
/**
 * Maps directly onto a `Cut { kind: Remove, reason: AiSuggested, .. }`
 * — see `plan_to_remove_cuts` below. `confidence`, when present, is
 * carried through only for the frontend's Edit Plan Preview UI (a
 * future pass); this schema doesn't otherwise interpret it.
 */
{ type: "remove"; start_us: number; end_us: number; reason: string; confidence: number | null } | 
/**
 * Structural-only in this pass — see module doc comment "`Remove` vs.
 * `Zoom`" above for why real timeline application is deferred.
 */
{ type: "zoom"; start_us: number; end_us: number; scale: number; reason: string }
/**
 * The structured edit plan an `AIProvider` must produce instead of ever
 * mutating the timeline directly (master prompt §18).
 */
export type EditPlan = { version: number; operations: EditOperation[] }
export type Effect = { id: string; clip_id: string; kind: string; 
/**
 * Freeform, effect-kind-specific parameters. Kept as opaque JSON here
 * deliberately — the effect catalog/parameter schemas don't exist yet
 * (Phase 6+), so a closed Rust struct would just be guessing.
 */
params: JsonValue }
export type EncoderBackend = "software" | "nvenc" | "quick_sync" | "amf"
export type ExportState = { last_render_preset: string | null; last_capcut_draft_path: string | null }
export type FfmpegDiagnostics = { ffmpeg_path: string; ffprobe_path: string; ffmpeg_version: string; ffprobe_version: string; 
/**
 * Honest provenance note (master prompt §59/§78) — see
 * `crate::ffmpeg::binaries` module doc comment for the full story.
 */
source_note: string }
/**
 * Custom-dictionary support (§16 "Allow custom dictionary"): a caller
 * supplies additional words/phrases, and independently controls whether
 * the EN+VI built-ins are included at all (additive-by-default, but a
 * caller who wants ONLY their own dictionary can set `use_defaults: false`).
 */
export type FillerDictionary = { 
/**
 * Include `DEFAULT_EN_FILLERS` and `DEFAULT_VI_FILLERS`.
 */
use_defaults: boolean; 
/**
 * Additional words/phrases on top of (or, if `use_defaults` is false,
 * instead of) the built-in defaults. Matched with the same
 * tokenized/case-insensitive rules as the defaults.
 */
custom_dictionary: string[] }
export type FindReplaceOptions = { case_sensitive: boolean; whole_word: boolean }
export type HardwareEncoderReport = { encoders: DetectedEncoder[]; 
/**
 * The master prompt's own display example: `"Encoder: NVIDIA NVENC"` or
 * `"Encoder: CPU — libx264"`, for the H.264 codec (the common case);
 * the frontend can recompute this per-codec via `encoders` directly if
 * the user has chosen H.265/VP9.
 */
active_encoder_label: string }
/**
 * One detected highlight candidate/segment: `{start, end, score, title,
 * reason}` (master prompt §21's exact return shape).
 * 
 * `score` is `0.0..=100.0` — matching master prompt §21's own UI mockup
 * ("Score: 92"), a deliberate difference from the `0.0..=1.0` convention
 * `vad::provider::SpeechSegment::confidence`/`ai::edit_plan::EditOperation
 * ::Remove.confidence` use elsewhere in this crate, so a highlight score
 * reads the same way the master prompt's own example shows it rather than
 * silently rescaling a UI-facing number a second time.
 */
export type Highlight = { id: string; start_us: number; end_us: number; score: number; title: string; reason: string }
/**
 * Result alongside the highlights themselves, so a caller (and a test) can
 * tell whether the semantic (AI) signal actually ran without re-deriving it
 * from whether `ai_settings` was passed.
 */
export type HighlightDetectionResult = { highlights: Highlight[]; 
/**
 * `true` only if AI settings were provided and the AI call/parse
 * actually succeeded and its candidates were used. `false` means the
 * result came entirely from real local signals — never a silent
 * fallback the caller can't distinguish from "the AI path worked".
 */
used_ai_semantic_signal: boolean }
export type ImportResult = { source_path: string; media: MediaItem | null; error: AppErrorPayload | null }
/**
 * A model found actually installed on disk (master prompt §60 "Installed
 * models").
 */
export type InstalledModel = { id: ModelId; path: string; size_bytes: number }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type Keyframe = { id: string; clip_id: string; 
/**
 * One of `position_x | position_y | rotation | scale | alpha | volume`
 * and more as the property catalog grows (`docs/project-format.md`
 * leaves this open-ended) — kept as `String` rather than a closed enum
 * so adding a keyframeable property doesn't require a schema-breaking
 * migration.
 */
property: string; time_offset_us: number; value: number; 
/**
 * pyJianYingDraft hardcodes linear-only interpolation today (audit
 * §1); `curve` is a `String` (not a unit enum) so bezier/ease support
 * can be added later without another schema version bump.
 */
curve: string }
export type MediaItem = { id: string; kind: MediaKind; 
/**
 * Absolute or project-relative path.
 */
source_path: string; duration_us: number; width: number; height: number; fps: Rational; codec: string; bitrate: number; audio_channels: number; sample_rate: number; rotation_deg: number; 
/**
 * RFC3339 timestamp, or `None` if the source has no embedded creation
 * time.
 */
created_at: string | null; proxy_path: string | null; thumbnail_path: string | null }
export type MediaKind = "video" | "audio" | "image"
export type MediaLibraryEntry = { id: string; filename: string; path: string; kind: MediaKind; duration_us: number; width: number; height: number; tags: string[]; 
/**
 * RFC3339, from the source file's own metadata, if any.
 */
created_at: string | null; 
/**
 * RFC3339, when this row was added to the library.
 */
imported_at: string; thumbnail_path: string | null; proxy_path: string | null }
export type ModelCatalogEntry = { id: ModelId; 
/**
 * Real ggml filename on disk and in the Hugging Face repo, e.g.
 * `ggml-tiny.bin`. `large` maps to `ggml-large-v3.bin` — whisper.cpp's
 * upstream repo has published v1/v2/v3(/v3-turbo) large weights over
 * time; v3 is the current best-accuracy release as of this writing.
 */
filename: string; display_name: string; 
/**
 * Verified via a real HEAD request (module doc comment), not an
 * estimate.
 */
approx_size_bytes: number; 
/**
 * `true` for every model in this catalog (module doc comment:
 * English-only `.en` variants are not offered), kept as a field rather
 * than assumed so the frontend never has to hardcode "all models here
 * are multilingual" — master prompt §14 explicitly asks for
 * "language support" as a shown property.
 */
multilingual: boolean; download_url: string }
export type ModelId = "tiny" | "base" | "small" | "medium" | "large"
export type ProjectMeta = { id: string; name: string; 
/**
 * RFC3339 timestamp.
 */
created_at: string; 
/**
 * RFC3339 timestamp.
 */
modified_at: string; 
/**
 * semver of the app version that wrote this file.
 */
app_version: string }
/**
 * The unified project file (`project.json`). See `docs/project-format.md`
 * for the full design rationale — stable UUID-based ids everywhere,
 * non-destructive (never stores rendered pixels/audio), versioned for
 * forward migration.
 */
export type ProjectV1 = { 
/**
 * Always `1` for this schema version. `ProjectV1::migrate_to_latest`
 * dispatches on this field.
 */
version: number; project: ProjectMeta; canvas: CanvasV1; media: MediaItem[]; tracks: Track[]; clips: Clip[]; captions: Caption[]; 
/**
 * Additive (Phase 8, master prompt §26) — the catalog of caption
 * styles this project has, referenced by `Caption::style_id`. Empty for
 * any project saved before this field existed; built-in templates
 * (`crate::captions::styles::all_caption_templates`) are not
 * auto-copied in here — same "catalog is separate from the user's own
 * list" relationship `render::RenderPreset` has with `RenderSettings`.
 */
caption_styles: CaptionStyle[]; transcript: TranscriptEntry[]; effects: Effect[]; animations: Animation[]; keyframes: Keyframe[]; cuts: Cut[]; ai: AiState; export: ExportState; sync_groups: SyncGroup[] }
export type ProxyMode = "off" | "auto" | "always"
/**
 * A rational number, used for frame rates (`num/den`, e.g. 30000/1001 for
 * 29.97 fps) to avoid the float-drift problems documented in autocut's
 * `timecode.rs` (audit §2/§5).
 */
export type Rational = { num: number; den: number }
export type RenderPreset = { id: string; name: string; description: string; settings: RenderSettings }
/**
 * Full, independently-overridable render configuration. A preset
 * (`RenderPreset::settings`) is just one concrete value of this struct.
 */
export type RenderSettings = { width: number; height: number; fps: Rational; container: Container; video_codec: VideoCodec; 
/**
 * `libx264`/`libx265`'s `-preset` speed/efficiency knob (`ultrafast`..
 * `veryslow`); ignored for `Vp9` and for hardware encoder backends
 * (each of which has its own, differently-named speed knob — out of
 * scope to expose individually here, see `plan::video_encoder_args`
 * doc comment). Owned `String` (not `&'static str`) so a user override
 * value (`commands::render::RenderSettingsInput::x264_preset`) doesn't
 * need a `'static` lifetime hack to plug in here.
 */
x264_preset: string; 
/**
 * `None` means "use `video_bitrate_kbps` instead" (bitrate-controlled
 * encode); hardware encoder backends always use bitrate mode (see
 * `plan.rs`), since NVENC/QSV/AMF do not share libx264/265's CRF scale.
 */
crf: number | null; video_bitrate_kbps: number | null; audio_codec: AudioCodec; audio_bitrate_kbps: number; 
/**
 * `None` = auto-detect the best available hardware encoder at render
 * time (falling back to software); `Some(Software)` forces libx264/265;
 * `Some(other)` forces that specific hardware backend if a working
 * encoder was actually detected for it (see `hwaccel::detect_encoders`),
 * erroring rather than silently downgrading if it wasn't.
 */
hardware_encoder: EncoderBackend | null }
/**
 * What the frontend actually sends: an optional preset id to seed from,
 * plus any fields the user overrode. `None` fields fall back to the
 * preset's value (or, with no preset, to the 1080p preset's defaults —
 * documented here rather than silently picking something arbitrary).
 */
export type RenderSettingsInput = { preset_id: string | null; width: number | null; height: number | null; fps: Rational | null; container: Container | null; video_codec: VideoCodec | null; x264_preset: string | null; crf: number | null; video_bitrate_kbps: number | null; audio_codec: AudioCodec | null; audio_bitrate_kbps: number | null; 
/**
 * `None` = auto-detect the best available hardware encoder, falling
 * back to software (master prompt §33). `Some(_)` requests a specific
 * backend, itself falling back to software if that hardware isn't
 * actually working on this machine (`hwaccel::resolve_backend_for_render`).
 */
hardware_encoder: EncoderBackend | null }
/**
 * Fractional (`0.0..=1.0`) inset from each canvas edge that caption
 * placement should stay clear of (master prompt §26 "safe margins") —
 * e.g. to avoid a platform's own UI chrome (TikTok's caption/like/share
 * buttons) overlapping generated captions.
 */
export type SafeMargins = { top: number; bottom: number; left: number; right: number }
/**
 * Static, build-time facts about this build. No telemetry, no network
 * calls, nothing environment-dependent beyond `std::env::consts`. Exists in
 * Phase 2 to exercise the Rust -> specta -> TypeScript pipeline end-to-end
 * with a genuinely working command; the full Settings > About / "Copy
 * System Information" panel (master prompt §78) is Phase 12 scope.
 */
export type ShellInfo = { app_version: string; tauri_version: string; os: string; arch: string }
/**
 * Master prompt §19's exact action list. Closed enum, `#[serde(tag =
 * "type")]` — same "no free-form string ever gets pattern-matched or
 * interpreted at runtime" discipline as `ai::edit_plan::EditOperation`
 * (that module's doc comment explains the master prompt §53 threat model
 * this defends against; identical reasoning applies here).
 */
export type SmartEditAction = 
/**
 * No-op on the timeline: the user/AI judged this span should stay
 * exactly as-is.
 */
{ type: "keep" } | 
/**
 * Maps to one `Cut` spanning the recommendation's whole
 * `start_us..end_us` — see [`recommendations_to_cuts`].
 */
{ type: "remove" } | 
/**
 * Maps to one `Cut` trimming the recommendation's span down to
 * `target_duration_us` — see module doc comment ("Shorten's exact
 * timeline interpretation") and [`recommendations_to_cuts`].
 */
{ type: "shorten"; target_duration_us: number } | 
/**
 * No-op on the timeline: a user-facing "this span is worth calling
 * out" verdict, distinct from Phase 10's separate highlight-detection
 * feature (module doc comment).
 */
{ type: "highlight" }
/**
 * Master prompt §19's exact category list.
 */
export type SmartEditCategory = "repetition" | "false_start" | "off_topic" | "weak_sentence" | "long_pause" | "filler_word" | "unnecessary_intro" | "duplicate_idea" | "boring_section"
/**
 * A single Smart Edit recommendation. Every field master prompt §19
 * requires ("time range, transcript, reason, confidence, suggested
 * action") plus `id` (so a frontend/caller can reference one recommendation
 * across the propose -> user-reviews -> apply round trip) and `category`
 * (which of §19's nine categories this recommendation falls under).
 * 
 * Closed, strictly typed, specta-typed for eventual frontend consumption —
 * this is a *proposal the user reviews*, never auto-applied (master prompt
 * §53's discipline, same as `EditPlan`).
 */
export type SmartEditRecommendation = { id: string; start_us: number; end_us: number; 
/**
 * The actual transcript text this recommendation is about — not just a
 * time range, so a user can judge the recommendation without having to
 * scrub the timeline first.
 */
transcript: string; category: SmartEditCategory; reason: string; confidence: number; suggested_action: SmartEditAction }
/**
 * A detected speech region, master prompt §13's `{start, end, confidence}`
 * return shape.
 * 
 * `confidence` does not exist in autocut's own `SpeechSegment` (its version
 * is `{start, end}` only in f64 seconds) — master prompt §13 explicitly
 * asks for one, so this is a new derived value: the mean of the per-chunk
 * probabilities that fell inside this segment after hysteresis grouping
 * (computed in `segments_from_scores`). Mean rather than min was chosen so
 * a single marginal chunk sitting right at the hysteresis release threshold
 * doesn't tank an otherwise-confident segment's reported score.
 */
export type SpeechSegment = { start_us: number; end_us: number; confidence: number }
/**
 * Generalizes autocut's fixed-camera-rig "shared cutlist + per-track
 * offset" concept (audit §4) into a first-class, optional relationship. A
 * clip's `Clip::group_id` points at a `SyncGroup`; the timeline engine
 * (Phase 4) propagates split/trim/delete across all members unless the
 * user explicitly ungroups.
 */
export type SyncGroup = { id: string; 
/**
 * Clips that must move/trim/cut together.
 */
clip_ids: string[]; 
/**
 * Relative alignment, keyed by clip id.
 */
offsets_us: Partial<{ [key in string]: number }> }
export type ThumbnailStripFrame = { timestamp_us: number; path: string }
export type Track = { id: string; kind: TrackKind; name: string; 
/**
 * Stacking order; higher draws on top (pyJianYingDraft convention,
 * audit §1).
 */
render_index: number; locked: boolean; hidden: boolean; muted: boolean; solo: boolean; 
/**
 * Ordered; the clips themselves live in `ProjectV1::clips`, keyed by
 * id — never store clip data inline here (stable-ID references only,
 * master prompt §5).
 */
clip_ids: string[] }
export type TrackKind = "video" | "audio" | "caption" | "image" | "overlay" | "effect"
/**
 * Sentence/segment-level transcript entry, extended (Phase 7, master
 * prompt §14 "Prefer word-level timestamps") with a `words` breakdown —
 * additive, pre-1.0 internal schema evolution, mirroring `Caption`'s
 * existing `words: Vec<Word>` field above rather than inventing a second
 * shape for the same idea. Empty (`vec![]`) for any entry produced before
 * this field existed, or by a transcription provider that only reports
 * segment-level timing.
 */
export type TranscriptEntry = { id: string; media_id: string; text: string; start_us: number; end_us: number; confidence: number; words: Word[]; is_filler: boolean }
/**
 * Segmentation parameters — everything `segments_from_scores` needs, and
 * nothing `score_chunks` needs (see module doc comment). i64-microsecond
 * counterpart of autocut's `VadParams` (which used `u32` milliseconds).
 */
export type VadParams = { threshold: number; min_silence_us: number; min_speech_us: number }
/**
 * Result of `score_media_silence` — deliberately does not carry the raw
 * `Vec<f32>` scores back over IPC (potentially ~100k+ floats for a long
 * file); they stay server-side in `VadCache`, keyed by `media_id`, and
 * `segment_media_silence` reads them back by id.
 */
export type VadScoreSummary = { media_id: string; chunk_count: number; chunk_duration_us: number; sample_count: number }
export type VideoCodec = "h264" | "h265" | "vp_9"
export type WaveformResult = { 
/**
 * Peak `|sample|` per bin, normalized to `[0, 1]`.
 */
peaks: number[]; 
/**
 * Microseconds spanned by one bin (`source_duration_us / peaks.len()`,
 * rounded). `0` if `peaks` is empty.
 */
bin_duration_us: number }
export type Word = { text: string; start_us: number; end_us: number; confidence: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
