
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getShellInfo() : Promise<ShellInfo> {
    return await TAURI_INVOKE("get_shell_info");
},
/**
 * Constructs a brand-new, in-memory `ProjectV1` with sensible defaults.
 * Deliberately does not touch the filesystem: wiring this into a real
 * Project Manager UI (recent projects, save/open, `project.json` on disk)
 * is later-phase work. This command exists in Phase 2 to exercise the real
 * `ProjectV1` schema (`docs/project-format.md`) end-to-end over IPC and
 * through specta-generated TypeScript types — it is not a placeholder for
 * "create project" functionality, just proof the schema/IPC layer works.
 */
async newProject(name: string) : Promise<ProjectV1> {
    return await TAURI_INVOKE("new_project", { name });
},
async ffmpegDiagnostics() : Promise<Result<FfmpegDiagnostics, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ffmpeg_diagnostics") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async probeMediaFile(path: string) : Promise<Result<MediaItem, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("probe_media_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Import an explicit list of files (drag & drop, multi-select file picker).
 * Never aborts on the first bad file — each path gets its own
 * success/error result so a multi-file drop of 50 files with one corrupt
 * clip still imports the other 49 (master prompt §7 "multi-file import").
 */
async importMediaPaths(paths: string[], proxyMode: ProxyMode) : Promise<Result<ImportResult[], AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_media_paths", { paths, proxyMode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Recursively import every supported file under `folder` (master prompt §7
 * "folder import").
 */
async importMediaFolder(folder: string, proxyMode: ProxyMode) : Promise<Result<ImportResult[], AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_media_folder", { folder, proxyMode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * On-demand proxy (re)generation, e.g. a user flipping Proxy mode from Off
 * to Always after already importing. Runs synchronously from the caller's
 * point of view (returns the final path or error) while still emitting the
 * same `media:proxy-progress` events a background import-triggered job
 * would, so one UI progress bar handles both cases.
 */
async generateMediaProxy(mediaId: string, sourcePath: string, mode: ProxyMode) : Promise<Result<string | null, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_media_proxy", { mediaId, sourcePath, mode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async computeMediaWaveform(path: string, bins: number) : Promise<Result<WaveformResult, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("compute_media_waveform", { path, bins }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Generates `count` evenly-spaced frame thumbnails across `[0, duration_us)`
 * for the Phase 4 timeline's clip filmstrip display (master prompt §10
 * "thumbnail strip"). Thin IPC wiring only, per this task's narrow-command
 * exception: reuses the exact same `media::thumbnail::generate_video_thumbnail`
 * single-frame extractor Phase 3 already implemented and tested for the
 * media-library card thumbnail — this command just calls it `count` times
 * at different timestamps. Results are cached under this media id's cache
 * directory (`{media_cache}/{media_id}/strip/{index}.jpg`) so a repeat call
 * for the same media/count (e.g. re-requesting the strip after a zoom
 * change) skips regenerating frames that already exist on disk.
 */
async generateThumbnailStrip(mediaId: string, sourcePath: string, durationUs: number, count: number) : Promise<Result<ThumbnailStripFrame[], AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_thumbnail_strip", { mediaId, sourcePath, durationUs, count }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchMediaLibrary(query: string | null, kind: MediaKind | null, limit: number) : Promise<Result<MediaLibraryEntry[], AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_media_library", { query, kind, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listMediaLibrary(limit: number) : Promise<Result<MediaLibraryEntry[], AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_media_library", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeMediaFromLibrary(id: string) : Promise<Result<null, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_media_from_library", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Loads `project` into the timeline session, replacing whatever was there
 * (fresh undo history, empty clipboard). Called whenever the frontend
 * opens or creates a project.
 */
async loadTimelineProject(project: ProjectV1) : Promise<void> {
    await TAURI_INVOKE("load_timeline_project", { project });
},
/**
 * Fetches the current in-session project (e.g. after a reload, or just to
 * resync).
 */
async getTimelineProject() : Promise<Result<ProjectV1, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_timeline_project") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async splitClip(clipId: string, splitAtUs: number) : Promise<Result<ProjectV1, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("split_clip", { clipId, splitAtUs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async trimClipStart(clipId: string, newStartUs: number) : Promise<Result<ProjectV1, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("trim_clip_start", { clipId, newStartUs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async trimClipEnd(clipId: string, newEndUs: number) : Promise<Result<ProjectV1, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("trim_clip_end", { clipId, newEndUs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async moveClip(clipId: string, targetTrackId: string, newPositionUs: number) : Promise<Result<ProjectV1, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("move_clip", { clipId, targetTrackId, newPositionUs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteClip(clipId: string) : Promise<Result<ProjectV1, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_clip", { clipId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes every clip in `clip_ids` as one atomic undo step — the
 * backend-side multi-select delete (master prompt §11's "composite/batch
 * command" requirement) so the frontend never needs N separate undo
 * entries for one multi-select action.
 */
async deleteClips(clipIds: string[]) : Promise<Result<ProjectV1, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_clips", { clipIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async duplicateClip(clipId: string, newPositionUs: number, targetTrackId: string | null) : Promise<Result<ProjectV1, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("duplicate_clip", { clipId, newPositionUs, targetTrackId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setTrackLocked(trackId: string, locked: boolean) : Promise<Result<ProjectV1, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_track_locked", { trackId, locked }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setTrackHidden(trackId: string, hidden: boolean) : Promise<Result<ProjectV1, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_track_hidden", { trackId, hidden }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setTrackMuted(trackId: string, muted: boolean) : Promise<Result<ProjectV1, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_track_muted", { trackId, muted }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setTrackSolo(trackId: string, solo: boolean) : Promise<Result<ProjectV1, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_track_solo", { trackId, solo }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Pure query, keyed by track id: whether solo state on any audio track
 * currently makes this track's audio effectively muted (master prompt: "if
 * any track has solo = true, all non-solo audio tracks are effectively
 * muted"). For the render/preview layer to consult; not itself an undoable
 * edit.
 */
async effectiveTrackMuteState() : Promise<Result<Partial<{ [key in string]: boolean }>, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("effective_track_mute_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async undoTimeline() : Promise<Result<ProjectV1, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("undo_timeline") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async redoTimeline() : Promise<Result<ProjectV1, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("redo_timeline") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async copyClips(clipIds: string[]) : Promise<Result<null, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("copy_clips", { clipIds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pasteClips(targetTrackId: string | null, targetPositionUs: number) : Promise<Result<ProjectV1, AppErrorPayload>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("paste_clips", { targetTrackId, targetPositionUs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Given a target time and a set of candidate snap points (other clip
 * edges, the playhead, markers — supplied by the frontend, which owns that
 * UI-level knowledge), returns the nearest candidate within `threshold_us`,
 * or `None`. Pure function, no session required.
 */
async snapToCandidates(targetUs: number, candidates: number[], thresholdUs: number) : Promise<number | null> {
    return await TAURI_INVOKE("snap_to_candidates", { targetUs, candidates, thresholdUs });
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AiState = { 
/**
 * Opaque id — actual credentials live in the Windows Credential
 * Manager, never in `project.json` (master prompt §17, Phase 10).
 */
provider_settings_ref: string | null; 
/**
 * Most recent `EditPlan` JSON (`docs/ai-engine.md`, Phase 10). Opaque
 * here for the same reason as `Effect::params`: the schema doesn't
 * exist yet.
 */
last_edit_plan: JsonValue | null; highlights: JsonValue[] }
export type Animation = { id: string; clip_id: string; kind: AnimationKind; name: string; duration_us: number }
export type AnimationKind = "in" | "out" | "loop" | "group"
export type AppErrorPayload = { code: string; message: string; details: string | null; recoverable: boolean; suggested_action: string | null }
export type CanvasRatioPreset = "16:9" | "9:16" | "1:1" | "4:5" | "custom"
export type CanvasV1 = { width: number; height: number; fps: Rational; ratio_preset: CanvasRatioPreset }
export type Caption = { id: string; track_id: string; start_us: number; end_us: number; text: string; words: Word[]; style_id: string | null }
export type Clip = { id: string; track_id: string; 
/**
 * `None` for e.g. a pure-effect or generated-caption clip.
 */
media_id: string | null; 
/**
 * Trim into the source media.
 */
source_in_us: number; source_out_us: number; 
/**
 * Placement on the track's timeline.
 */
position_us: number; speed: number; enabled: boolean; 
/**
 * `SyncGroup` membership, see `SyncGroup` below.
 */
group_id: string | null; clip_settings: ClipSettings }
export type ClipSettings = { opacity: number; flip_h: boolean; flip_v: boolean; rotation_deg: number; scale_x: number; scale_y: number; 
/**
 * Half-canvas-width/height units, matching pyJianYingDraft's
 * `transform_x`/`transform_y` convention (audit §1) — NOT pixels. A
 * frequent bug source upstream; documented here so it isn't
 * rediscovered the hard way in the render/capcut adapters.
 */
transform_x: number; transform_y: number }
/**
 * Edit-plan / silence-removal provenance — NOT a duplicate timeline.
 * Records *why* clips were split/removed by an automated pass (VAD, AI
 * EditPlan), for undo/audit/re-analysis (`docs/project-format.md`).
 */
export type Cut = { id: string; kind: CutKind; source_media_id: string; start_us: number; end_us: number; reason: CutReason; applied: boolean }
export type CutKind = "remove" | "keep"
export type CutReason = "silence" | "filler_word" | "ai_suggested"
export type Effect = { id: string; clip_id: string; kind: string; 
/**
 * Freeform, effect-kind-specific parameters. Kept as opaque JSON here
 * deliberately — the effect catalog/parameter schemas don't exist yet
 * (Phase 6+), so a closed Rust struct would just be guessing.
 */
params: JsonValue }
export type ExportState = { last_render_preset: string | null; last_capcut_draft_path: string | null }
export type FfmpegDiagnostics = { ffmpeg_path: string; ffprobe_path: string; ffmpeg_version: string; ffprobe_version: string; 
/**
 * Honest provenance note (master prompt §59/§78) — see
 * `crate::ffmpeg::binaries` module doc comment for the full story.
 */
source_note: string }
export type ImportResult = { source_path: string; media: MediaItem | null; error: AppErrorPayload | null }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type Keyframe = { id: string; clip_id: string; 
/**
 * One of `position_x | position_y | rotation | scale | alpha | volume`
 * and more as the property catalog grows (`docs/project-format.md`
 * leaves this open-ended) — kept as `String` rather than a closed enum
 * so adding a keyframeable property doesn't require a schema-breaking
 * migration.
 */
property: string; time_offset_us: number; value: number; 
/**
 * pyJianYingDraft hardcodes linear-only interpolation today (audit
 * §1); `curve` is a `String` (not a unit enum) so bezier/ease support
 * can be added later without another schema version bump.
 */
curve: string }
export type MediaItem = { id: string; kind: MediaKind; 
/**
 * Absolute or project-relative path.
 */
source_path: string; duration_us: number; width: number; height: number; fps: Rational; codec: string; bitrate: number; audio_channels: number; sample_rate: number; rotation_deg: number; 
/**
 * RFC3339 timestamp, or `None` if the source has no embedded creation
 * time.
 */
created_at: string | null; proxy_path: string | null; thumbnail_path: string | null }
export type MediaKind = "video" | "audio" | "image"
export type MediaLibraryEntry = { id: string; filename: string; path: string; kind: MediaKind; duration_us: number; width: number; height: number; tags: string[]; 
/**
 * RFC3339, from the source file's own metadata, if any.
 */
created_at: string | null; 
/**
 * RFC3339, when this row was added to the library.
 */
imported_at: string; thumbnail_path: string | null; proxy_path: string | null }
export type ProjectMeta = { id: string; name: string; 
/**
 * RFC3339 timestamp.
 */
created_at: string; 
/**
 * RFC3339 timestamp.
 */
modified_at: string; 
/**
 * semver of the app version that wrote this file.
 */
app_version: string }
/**
 * The unified project file (`project.json`). See `docs/project-format.md`
 * for the full design rationale — stable UUID-based ids everywhere,
 * non-destructive (never stores rendered pixels/audio), versioned for
 * forward migration.
 */
export type ProjectV1 = { 
/**
 * Always `1` for this schema version. `ProjectV1::migrate_to_latest`
 * dispatches on this field.
 */
version: number; project: ProjectMeta; canvas: CanvasV1; media: MediaItem[]; tracks: Track[]; clips: Clip[]; captions: Caption[]; transcript: TranscriptEntry[]; effects: Effect[]; animations: Animation[]; keyframes: Keyframe[]; cuts: Cut[]; ai: AiState; export: ExportState; sync_groups: SyncGroup[] }
export type ProxyMode = "off" | "auto" | "always"
/**
 * A rational number, used for frame rates (`num/den`, e.g. 30000/1001 for
 * 29.97 fps) to avoid the float-drift problems documented in autocut's
 * `timecode.rs` (audit §2/§5).
 */
export type Rational = { num: number; den: number }
/**
 * Static, build-time facts about this build. No telemetry, no network
 * calls, nothing environment-dependent beyond `std::env::consts`. Exists in
 * Phase 2 to exercise the Rust -> specta -> TypeScript pipeline end-to-end
 * with a genuinely working command; the full Settings > About / "Copy
 * System Information" panel (master prompt §78) is Phase 12 scope.
 */
export type ShellInfo = { app_version: string; tauri_version: string; os: string; arch: string }
/**
 * Generalizes autocut's fixed-camera-rig "shared cutlist + per-track
 * offset" concept (audit §4) into a first-class, optional relationship. A
 * clip's `Clip::group_id` points at a `SyncGroup`; the timeline engine
 * (Phase 4) propagates split/trim/delete across all members unless the
 * user explicitly ungroups.
 */
export type SyncGroup = { id: string; 
/**
 * Clips that must move/trim/cut together.
 */
clip_ids: string[]; 
/**
 * Relative alignment, keyed by clip id.
 */
offsets_us: Partial<{ [key in string]: number }> }
export type ThumbnailStripFrame = { timestamp_us: number; path: string }
export type Track = { id: string; kind: TrackKind; name: string; 
/**
 * Stacking order; higher draws on top (pyJianYingDraft convention,
 * audit §1).
 */
render_index: number; locked: boolean; hidden: boolean; muted: boolean; solo: boolean; 
/**
 * Ordered; the clips themselves live in `ProjectV1::clips`, keyed by
 * id — never store clip data inline here (stable-ID references only,
 * master prompt §5).
 */
clip_ids: string[] }
export type TrackKind = "video" | "audio" | "caption" | "image" | "overlay" | "effect"
export type TranscriptEntry = { id: string; media_id: string; text: string; start_us: number; end_us: number; confidence: number; is_filler: boolean }
export type WaveformResult = { 
/**
 * Peak `|sample|` per bin, normalized to `[0, 1]`.
 */
peaks: number[]; 
/**
 * Microseconds spanned by one bin (`source_duration_us / peaks.len()`,
 * rounded). `0` if `peaks` is empty.
 */
bin_duration_us: number }
export type Word = { text: string; start_us: number; end_us: number; confidence: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
