//! `EditPlan` JSON schema + strict validation (master prompt §18/§53).
//!
//! "AI must NEVER directly mutate the timeline. AI produces a structured
//! edit plan" which then goes through "JSON Schema validation" before any
//! "Edit Plan Preview → User Approves → Timeline Engine" step. This module
//! is the validation stage: [`parse_and_validate`] is the *only* way a raw
//! string (whatever text an `AIProvider` handed back) becomes an `EditPlan`
//! this crate will act on, and it never partially succeeds — any rejection
//! returns an [`EditPlanError`] and no `EditPlan` value at all.
//!
//! ## Why `EditOperation` is a closed enum, not a `type: String` field
//!
//! Master prompt §53: "Do not execute arbitrary shell commands generated by
//! AI." The concrete mechanism here is that [`EditOperation`]'s `#[serde(tag
//! = "type")]` enum has a fixed, compile-time-closed set of variants with
//! typed fields — there is no `String` anywhere that gets pattern-matched or
//! interpreted as a command at runtime. An AI response naming an operation
//! type this app doesn't know about (or, hypothetically, trying to smuggle
//! a shell command through a `type` field) simply **fails to deserialize**
//! — `serde` rejects it before any application code ever sees it. This is a
//! structural guarantee, not a validation rule that could be forgotten.
//!
//! ## `Remove` vs. `Zoom`: which operations actually apply, and why
//!
//! - **`Remove` is real.** It maps directly onto this crate's existing
//!   `Cut`/`timeline::silence` infrastructure (`plan_to_remove_cuts` below
//!   builds real `Cut { kind: Remove, reason: AiSuggested, .. }` values,
//!   applied through the exact same `apply_cuts_to_clip`/
//!   `apply_cuts_to_track` → `Command::Batch` path VAD/filler-word cuts
//!   already use — see `commands::ai::apply_edit_plan_to_clip`/
//!   `apply_edit_plan_to_track`).
//! - **`Zoom` is structural-only in this pass.** It is represented here
//!   (closed enum variant, strictly validated) exactly per master prompt
//!   §18's own example, but this pass does not implement its *application*
//!   to the timeline. Checked against `project::types`: `Keyframe` exists
//!   (`{clip_id, property, time_offset_us, value, curve}`) and could in
//!   principle carry a `scale` keyframe pair, but there is no
//!   keyframe-authoring UI or "which clip does this zoom target" resolution
//!   logic anywhere yet in this codebase — inventing that mapping now, with
//!   no real caller and no UI to author/preview it, would be guessing at a
//!   design a future pass (which owns Smart Edit / auto-zoom, per
//!   `IMPLEMENTATION_PLAN.md` Phase 10/11) is better positioned to get
//!   right. A `Zoom` operation therefore parses and validates cleanly but
//!   `commands::ai::apply_edit_plan_to_clip`/`_to_track` silently ignore it
//!   (same "ignore what this pass doesn't handle" shape
//!   `timeline::silence::apply_cuts_to_track` already uses for clips with no
//!   media — module doc comment there), never partially/incorrectly
//!   "applying" it.

use serde::{Deserialize, Serialize};
use specta::Type;

use crate::project::{Cut, CutKind, CutReason};

use super::error::EditPlanError;

/// The only schema version this app understands today. `EditPlan::version`
/// must equal this exactly — not "less than or equal", since a lower
/// version number would imply a schema this app has never actually spoken
/// and has no migration logic for either.
pub const CURRENT_VERSION: u32 = 1;

/// A single edit action (master prompt §18's example: `{"type": "remove",
/// "start": 12.3, "end": 15.7, "reason": "long pause"}` /
/// `{"type": "zoom", "start": 32, "end": 36, "scale": 1.12}`). Time fields
/// are `_us` microseconds per this crate's own timebase convention
/// (`project::types` module doc comment), not the master prompt's own
/// float-seconds example — every other timestamp in this schema
/// (`Cut`/`Clip`/`Caption`/...) already made that same conversion.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Type)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum EditOperation {
    /// Maps directly onto a `Cut { kind: Remove, reason: AiSuggested, .. }`
    /// — see `plan_to_remove_cuts` below. `confidence`, when present, is
    /// carried through only for the frontend's Edit Plan Preview UI (a
    /// future pass); this schema doesn't otherwise interpret it.
    Remove {
        start_us: i64,
        end_us: i64,
        reason: String,
        confidence: Option<f32>,
    },
    /// Structural-only in this pass — see module doc comment "`Remove` vs.
    /// `Zoom`" above for why real timeline application is deferred.
    Zoom {
        start_us: i64,
        end_us: i64,
        scale: f64,
        reason: String,
    },
}

/// The structured edit plan an `AIProvider` must produce instead of ever
/// mutating the timeline directly (master prompt §18).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Type)]
pub struct EditPlan {
    pub version: u32,
    pub operations: Vec<EditOperation>,
}

/// Parses `raw` (whatever text an `AIProvider::complete` returned) as JSON
/// and validates it against the strict `EditPlan` schema. Never partially
/// applies: any rejection returns an `Err` and no `EditPlan` at all — the
/// caller (`commands::ai::validate_edit_plan`) gets a clear, specific
/// validation error to show the user rather than a silently-coerced or
/// partially-populated plan.
///
/// Validation, in order:
/// 1. `raw` must parse as valid JSON matching `EditPlan`'s shape at all
///    (a malformed document, or one naming an operation `type` outside the
///    closed `EditOperation` enum, fails here — `EditPlanError::MalformedJson`).
/// 2. `version` must equal [`CURRENT_VERSION`] exactly
///    (`EditPlanError::UnsupportedVersion`).
/// 3. Every operation's fields must be in-range
///    (`EditPlanError::InvalidOperation`, carrying the offending index):
///    - `start_us` must be `>= 0`.
///    - `end_us` must be strictly greater than `start_us` (rejects zero and
///      negative/inverted durations in one check).
///    - `Remove.confidence`, if present, must be within `0.0..=1.0`.
///    - `Zoom.scale` must be finite and strictly positive (rejects zero,
///      negative, NaN, and infinite scale).
pub fn parse_and_validate(raw: &str) -> Result<EditPlan, EditPlanError> {
    let plan: EditPlan = serde_json::from_str(raw).map_err(|e| EditPlanError::MalformedJson {
        details: e.to_string(),
    })?;

    if plan.version != CURRENT_VERSION {
        return Err(EditPlanError::UnsupportedVersion {
            version: plan.version,
        });
    }

    for (index, op) in plan.operations.iter().enumerate() {
        validate_operation(index, op)?;
    }

    Ok(plan)
}

fn validate_operation(index: usize, op: &EditOperation) -> Result<(), EditPlanError> {
    let invalid = |details: String| EditPlanError::InvalidOperation { index, details };

    match op {
        EditOperation::Remove {
            start_us,
            end_us,
            confidence,
            ..
        } => {
            validate_time_range(*start_us, *end_us).map_err(invalid)?;
            if let Some(c) = confidence {
                if !(0.0..=1.0).contains(c) {
                    return Err(invalid(format!(
                        "confidence must be within 0.0..=1.0, got {c}"
                    )));
                }
            }
            Ok(())
        }
        EditOperation::Zoom {
            start_us,
            end_us,
            scale,
            ..
        } => {
            validate_time_range(*start_us, *end_us).map_err(invalid)?;
            if !scale.is_finite() || *scale <= 0.0 {
                return Err(invalid(format!(
                    "scale must be a finite number > 0.0, got {scale}"
                )));
            }
            Ok(())
        }
    }
}

fn validate_time_range(start_us: i64, end_us: i64) -> Result<(), String> {
    if start_us < 0 {
        return Err(format!("start_us must be >= 0, got {start_us}"));
    }
    if end_us <= start_us {
        return Err(format!(
            "end_us ({end_us}) must be greater than start_us ({start_us})"
        ));
    }
    Ok(())
}

/// Converts every `Remove` operation in `plan` into a real, unapplied
/// `Cut` (`kind: Remove, reason: AiSuggested`) scoped to `source_media_id` —
/// the exact shape `timeline::silence::apply_cuts_to_clip`/
/// `apply_cuts_to_track` already know how to turn into split/trim/delete
/// `Command`s (module doc comment's "`Remove` is real"). `Zoom` operations
/// are skipped — not an error, just not yet representable as a `Cut`.
///
/// `source_media_id` is not part of the `EditPlan` schema itself (an
/// `EditOperation::Remove`'s `start_us`/`end_us` are source-media-relative,
/// matching `Cut`'s own convention, but a plan has no built-in notion of
/// *which* media it was generated against — that context comes from
/// whichever caller produced the plan, exactly like `vad`'s cutlist
/// builder takes a `source_media_id` parameter rather than embedding one).
pub fn plan_to_remove_cuts(plan: &EditPlan, source_media_id: &str) -> Vec<Cut> {
    plan.operations
        .iter()
        .filter_map(|op| match op {
            EditOperation::Remove {
                start_us,
                end_us,
                reason: _reason,
                confidence: _,
            } => Some(Cut {
                id: uuid::Uuid::new_v4().to_string(),
                kind: CutKind::Remove,
                source_media_id: source_media_id.to_string(),
                start_us: *start_us,
                end_us: *end_us,
                reason: CutReason::AiSuggested,
                applied: false,
            }),
            EditOperation::Zoom { .. } => None,
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn valid_plan_json() -> &'static str {
        r#"{
            "version": 1,
            "operations": [
                {"type": "remove", "start_us": 100, "end_us": 200, "reason": "long pause", "confidence": 0.9},
                {"type": "zoom", "start_us": 300, "end_us": 400, "scale": 1.12, "reason": "emphasis"}
            ]
        }"#
    }

    #[test]
    fn a_valid_plan_parses_with_both_operation_kinds() {
        let plan = parse_and_validate(valid_plan_json()).unwrap();
        assert_eq!(plan.version, 1);
        assert_eq!(plan.operations.len(), 2);
        assert!(matches!(plan.operations[0], EditOperation::Remove { .. }));
        assert!(matches!(plan.operations[1], EditOperation::Zoom { .. }));
    }

    #[test]
    fn an_empty_operations_list_is_valid() {
        let plan = parse_and_validate(r#"{"version": 1, "operations": []}"#).unwrap();
        assert!(plan.operations.is_empty());
    }

    #[test]
    fn malformed_json_is_rejected() {
        let err = parse_and_validate("not json at all").unwrap_err();
        assert!(matches!(err, EditPlanError::MalformedJson { .. }));
    }

    #[test]
    fn an_unknown_operation_type_fails_to_deserialize() {
        let raw = r#"{"version": 1, "operations": [{"type": "delete_all_files", "start_us": 0, "end_us": 1}]}"#;
        let err = parse_and_validate(raw).unwrap_err();
        assert!(matches!(err, EditPlanError::MalformedJson { .. }));
    }

    #[test]
    fn a_shell_command_smuggled_into_an_unknown_type_field_still_fails_to_deserialize() {
        // The exact master-prompt §53 threat model: an AI response trying to
        // get *something* other than "remove"/"zoom" executed. There is no
        // code path that interprets `type` as anything but a closed enum
        // discriminant, so this can only ever fail to parse.
        let raw =
            r#"{"version": 1, "operations": [{"type": "rm -rf /", "start_us": 0, "end_us": 1}]}"#;
        assert!(matches!(
            parse_and_validate(raw).unwrap_err(),
            EditPlanError::MalformedJson { .. }
        ));
    }

    #[test]
    fn missing_operations_field_is_rejected() {
        let err = parse_and_validate(r#"{"version": 1}"#).unwrap_err();
        assert!(matches!(err, EditPlanError::MalformedJson { .. }));
    }

    #[test]
    fn an_unsupported_version_is_rejected() {
        let raw = r#"{"version": 2, "operations": []}"#;
        assert!(matches!(
            parse_and_validate(raw).unwrap_err(),
            EditPlanError::UnsupportedVersion { version: 2 }
        ));
    }

    #[test]
    fn version_zero_is_rejected() {
        let raw = r#"{"version": 0, "operations": []}"#;
        assert!(matches!(
            parse_and_validate(raw).unwrap_err(),
            EditPlanError::UnsupportedVersion { version: 0 }
        ));
    }

    #[test]
    fn negative_start_us_is_rejected() {
        let raw = r#"{"version": 1, "operations": [
            {"type": "remove", "start_us": -1, "end_us": 100, "reason": "x", "confidence": null}
        ]}"#;
        let err = parse_and_validate(raw).unwrap_err();
        assert!(matches!(
            err,
            EditPlanError::InvalidOperation { index: 0, .. }
        ));
    }

    #[test]
    fn end_us_equal_to_start_us_is_rejected() {
        let raw = r#"{"version": 1, "operations": [
            {"type": "remove", "start_us": 100, "end_us": 100, "reason": "x", "confidence": null}
        ]}"#;
        assert!(matches!(
            parse_and_validate(raw).unwrap_err(),
            EditPlanError::InvalidOperation { index: 0, .. }
        ));
    }

    #[test]
    fn inverted_time_range_is_rejected() {
        let raw = r#"{"version": 1, "operations": [
            {"type": "remove", "start_us": 200, "end_us": 100, "reason": "x", "confidence": null}
        ]}"#;
        assert!(matches!(
            parse_and_validate(raw).unwrap_err(),
            EditPlanError::InvalidOperation { index: 0, .. }
        ));
    }

    #[test]
    fn out_of_range_confidence_is_rejected() {
        let raw = r#"{"version": 1, "operations": [
            {"type": "remove", "start_us": 0, "end_us": 100, "reason": "x", "confidence": 1.5}
        ]}"#;
        assert!(matches!(
            parse_and_validate(raw).unwrap_err(),
            EditPlanError::InvalidOperation { index: 0, .. }
        ));
    }

    #[test]
    fn zero_scale_is_rejected() {
        let raw = r#"{"version": 1, "operations": [
            {"type": "zoom", "start_us": 0, "end_us": 100, "scale": 0.0, "reason": "x"}
        ]}"#;
        assert!(matches!(
            parse_and_validate(raw).unwrap_err(),
            EditPlanError::InvalidOperation { index: 0, .. }
        ));
    }

    #[test]
    fn negative_scale_is_rejected() {
        let raw = r#"{"version": 1, "operations": [
            {"type": "zoom", "start_us": 0, "end_us": 100, "scale": -1.0, "reason": "x"}
        ]}"#;
        assert!(matches!(
            parse_and_validate(raw).unwrap_err(),
            EditPlanError::InvalidOperation { index: 0, .. }
        ));
    }

    #[test]
    fn the_second_operations_index_is_reported_when_the_first_is_valid() {
        let raw = r#"{"version": 1, "operations": [
            {"type": "remove", "start_us": 0, "end_us": 100, "reason": "ok", "confidence": null},
            {"type": "zoom", "start_us": 0, "end_us": 100, "scale": -1.0, "reason": "x"}
        ]}"#;
        assert!(matches!(
            parse_and_validate(raw).unwrap_err(),
            EditPlanError::InvalidOperation { index: 1, .. }
        ));
    }

    #[test]
    fn plan_to_remove_cuts_only_includes_remove_operations() {
        let plan = parse_and_validate(valid_plan_json()).unwrap();
        let cuts = plan_to_remove_cuts(&plan, "media-1");
        assert_eq!(cuts.len(), 1);
        assert_eq!(cuts[0].source_media_id, "media-1");
        assert_eq!(cuts[0].start_us, 100);
        assert_eq!(cuts[0].end_us, 200);
        assert_eq!(cuts[0].kind, CutKind::Remove);
        assert_eq!(cuts[0].reason, CutReason::AiSuggested);
        assert!(!cuts[0].applied);
    }

    #[test]
    fn plan_to_remove_cuts_on_an_all_zoom_plan_is_empty() {
        let raw = r#"{"version": 1, "operations": [
            {"type": "zoom", "start_us": 0, "end_us": 100, "scale": 1.5, "reason": "x"}
        ]}"#;
        let plan = parse_and_validate(raw).unwrap();
        assert!(plan_to_remove_cuts(&plan, "media-1").is_empty());
    }

    #[test]
    fn round_trips_through_json_with_the_documented_type_tag() {
        let plan = EditPlan {
            version: 1,
            operations: vec![EditOperation::Remove {
                start_us: 12_300_000,
                end_us: 15_700_000,
                reason: "long pause".into(),
                confidence: Some(0.8),
            }],
        };
        let json = serde_json::to_value(&plan).unwrap();
        assert_eq!(json["operations"][0]["type"], "remove");
        let back: EditPlan = serde_json::from_value(json).unwrap();
        assert_eq!(back, plan);
    }

    /// The end-to-end integration proof this phase's brief asks for. A
    /// validated `EditPlan`'s `Remove` operations are converted to `Cut`s by
    /// `plan_to_remove_cuts`, then applied through the real
    /// `timeline::silence` and `timeline::command` machinery, the same path
    /// `commands::ai::apply_edit_plan_to_clip` reaches via
    /// `commands::timeline::apply_silence_cuts`, never a parallel
    /// AI-specific mutation path, as one atomic, undoable batch.
    #[test]
    fn edit_plan_remove_operations_apply_through_the_real_timeline_engine_as_one_undo_step() {
        use crate::project::{Clip, ClipSettings, ProjectV1, Track, TrackKind};
        use crate::timeline::command::{History, MAX_HISTORY};
        use crate::timeline::ops::clip_span;
        use crate::timeline::silence;

        let raw = r#"{"version": 1, "operations": [
            {"type": "remove", "start_us": 3000000, "end_us": 5000000, "reason": "long pause", "confidence": 0.95},
            {"type": "zoom", "start_us": 6000000, "end_us": 7000000, "scale": 1.2, "reason": "emphasis"}
        ]}"#;
        let plan = parse_and_validate(raw).expect("plan validates");

        let mut project = ProjectV1::new("ai edit plan integration test");
        project.tracks.push(Track {
            id: "t1".into(),
            kind: TrackKind::Video,
            name: "t1".into(),
            render_index: 0,
            locked: false,
            hidden: false,
            muted: false,
            solo: false,
            clip_ids: vec!["c1".into()],
        });
        project.clips.push(Clip {
            id: "c1".into(),
            track_id: "t1".into(),
            media_id: Some("m1".into()),
            source_in_us: 0,
            source_out_us: 10_000_000,
            position_us: 0,
            speed: 1.0,
            enabled: true,
            group_id: None,
            clip_settings: ClipSettings::default(),
        });
        let before = serde_json::to_value(&project).unwrap();

        let cuts = plan_to_remove_cuts(&plan, "m1");
        // The Zoom operation must not have produced a Cut (structural-only,
        // module doc comment).
        assert_eq!(cuts.len(), 1);

        let edit_command =
            silence::apply_cuts_to_clip(&project, "c1", &cuts).expect("cuts apply to the clip");

        let mut history = History::new(MAX_HISTORY);
        history
            .apply(&mut project, edit_command)
            .expect("batch applies as one undo step");

        // The interior [3s, 5s) removal split the 0..10s clip into two
        // surviving pieces, exactly like a VAD/filler-word Remove cut would.
        let mut spans: Vec<(i64, i64)> = project.clips.iter().map(clip_span).collect();
        spans.sort();
        assert_eq!(spans, vec![(0, 3_000_000), (5_000_000, 10_000_000)]);

        // One atomic undo step restores the original single clip exactly.
        history
            .undo(&mut project)
            .expect("undo restores original state");
        assert_eq!(serde_json::to_value(&project).unwrap(), before);

        // And redo reproduces the same split deterministically.
        history.redo(&mut project).expect("redo reapplies cleanly");
        let mut spans_after_redo: Vec<(i64, i64)> = project.clips.iter().map(clip_span).collect();
        spans_after_redo.sort();
        assert_eq!(
            spans_after_redo,
            vec![(0, 3_000_000), (5_000_000, 10_000_000)]
        );
    }
}
